export const spanishWords = [
  'ABRAZO', 'AGUA', 'ALEGRÍA', 'AMISTAD', 'ÁRBOL', 'AVENTURA', 'BIBLIOTECA',
  'BICICLETA', 'BOSQUE', 'CAFÉ', 'CAMIÓN', 'CANCIÓN', 'CARACOL', 'CASTILLO',
  'CHOCOLATE', 'CIUDAD', 'CORAZÓN', 'CUADERNO', 'DESIERTO', 'ELEFANTE',
  'ESTRELLA', 'FAMILIA', 'FANTASÍA', 'FÚTBOL', 'GIRASOL', 'GUITARRA',
  'HÉROE', 'INVIERNO', 'JARDÍN', 'JIRAFA', 'LÁMPARA', 'LIBÉLULA', 'LLUVIA',
  'MAÑANA', 'MARIPOSA', 'MONTAÑA', 'MÚSICA', 'NARANJA', 'NIÑEZ', 'OCÉANO',
  'PAÍS', 'PINGÜINO', 'PRIMAVERA', 'QUESO', 'RÍO', 'SUEÑO', 'TELÉFONO',
  'UNIVERSO', 'VERANO', 'ZAPATO',
] as const
