import assert from 'node:assert/strict'
import { GameRoom } from '../dist-server/server/game/GameRoom.js'

const room = new GameRoom('CHAT', 'es', null, () => 0.1)
room.addPlayer('p1', 's1', 't1', 'Sergio')

const first = room.addChatMessage('p1', '  Hola <img src=x onerror=alert(1)>  ')
assert.equal(first.senderId, 'p1')
assert.equal(first.senderName, 'Sergio')
assert.equal(first.text, 'Hola <img src=x onerror=alert(1)>')
assert.equal(typeof first.timestamp, 'number')
assert.deepEqual(first.reactions, { '❤️': [], '😂': [], '💀': [] })
assert.throws(() => room.addChatMessage('outsider', 'Hola'), /not-room-member/)
assert.throws(() => room.addChatMessage('p1', '   '), /empty-chat-message/)
assert.throws(() => room.addChatMessage('p1', 'x'.repeat(301)), /chat-message-too-long/)

for (let index = 0; index < 55; index += 1) room.addChatMessage('p1', `Mensaje ${index}`)
assert.equal(room.chatHistory.length, 50)
assert.equal(room.chatHistory[0].text, 'Mensaje 5')
assert.equal(room.chatHistory.at(-1)?.text, 'Mensaje 54')

room.addPlayer('p2', 's2', 't2', 'Marta')
const reactionMessage = room.addChatMessage('p1', 'Reacciona aquí')
room.toggleChatReaction('p1', reactionMessage.id, '💀')
assert.deepEqual(reactionMessage.reactions['💀'], ['p1'])
room.toggleChatReaction('p2', reactionMessage.id, '💀')
assert.deepEqual(reactionMessage.reactions['💀'], ['p1', 'p2'])
room.toggleChatReaction('p1', reactionMessage.id, '💀')
assert.deepEqual(reactionMessage.reactions['💀'], ['p2'])
room.toggleChatReaction('p1', reactionMessage.id, '❤️')
room.toggleChatReaction('p2', reactionMessage.id, '😂')
assert.deepEqual(reactionMessage.reactions['❤️'], ['p1'])
assert.deepEqual(reactionMessage.reactions['😂'], ['p2'])
assert.throws(() => room.toggleChatReaction('p1', reactionMessage.id, '🔥'), /invalid-reaction/)
assert.throws(() => room.toggleChatReaction('outsider', reactionMessage.id, '❤️'), /not-room-member/)

const otherRoom = new GameRoom('OTHER', 'es', null, () => 0.1)
otherRoom.addPlayer('p3', 's3', 't3', 'Otro')
assert.throws(() => otherRoom.toggleChatReaction('p3', reactionMessage.id, '❤️'), /chat-message-not-found/)

room.markReconnecting('p2', 's2')
room.resume('p2', 't2', 's2-next')
assert.deepEqual(room.chatHistory.find((message) => message.id === reactionMessage.id)?.reactions['💀'], ['p2'])
room.setWord('p1', 'CASA')
room.guess('p2', 'C')
assert.equal(room.chatHistory.length, 50)
room.addChatMessage('p2', 'Sigue aquí')
assert.equal(room.chatHistory.at(-1)?.senderName, 'Marta')

console.log('Chat validation and bounded-history checks passed')
